export const GET_REPOSITORIES_BY_USER_START = 'GET_REPOSITORIES_BY_USER_START';
export const GET_REPOSITORIES_BY_USER_COMPLETE = 'GET_REPOSITORIES_BY_USER_COMPLETE';
export const GET_REPOSITORIES_BY_USER_ERROR = 'GET_REPOSITORIES_BY_USER_ERROR';