export const GET_ALL_COMMITS_BY_PROYECT_SUCCESS = 'GET_ALL_COMMITS_BY_PROYECT_SUCCESS'
export const HANDLE_API_ERROR = 'HANDLE_API_ERROR'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_ALL_REPOSITORIES_BY_USER_SUCCESS = 'GET_ALL_REPOSITORIES_BY_USER_SUCCESS'